bot_title: "Bitcoin Wallet Viewer"

telegram_token : ''
allowed_user_ids:

update_each: 3600 # seconds
date_format: "%d/%m/%Y" # datetime compliant format
hour_format": "%H:%M" # datetime compliant format

money: "USD"
money_format: "en_US"

wallets:
  - name: Test Wallet
    address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2"
  - name: Test Wallet
    address: "aaa1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2"

# BOT STRINGS ---------------------------------------------
title:
  - "*{title}*"
wallet_view:
  - "\n\n*- {wallet}*"
  - "ðŸ’° *{btc_balance}* BTC"
  - "ðŸ’± *{money_balance}* in {currency}"
failed_wallet_view:
  - "\n\n*- {wallet}*"
  - "_Unable to fetch wallet information._"
extra_content:
  - "\n\n\nðŸ“ˆ *1BTC* is worth *{btc_value}*"
  - "\n_ðŸ•— Last update: {update_date} at {update_time}_"
update_button: "ðŸ”„"

updating:
  - "_Updating.._"
  - "_Updating..._"
  - "_Fetching information.._"
  - "_Fetching information..._"
  - "_Retrieving information.._"
  - "_Retrieving information..._"